import type { PropsWithChildren } from "react";
import "./global.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Welcome to docs",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-zinc-950">
        <Providers>{props.children}</Providers>
      </body>
    </html>
  );
}
