import "./global.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Welcome to docs",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-zinc-950">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
